name: base
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Python
  - python >=3.11,<3.12
  - icecream
  - natsort
  - pandas <2
  - seaborn
  - pyyaml
  # Other
  - pip
  - pip:
    - esgf-pyclient
